[package]
name = "neato_driver"
version = "0.1.0"
authors = ["Loy van Beek <loy.vanbeek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
